### PR TITLE
Make tile creator utility class

### PR DESCRIPTION
**Pull request by nanthony21**
While there are multiple components of micromanager that are interested in setting up a grid of positions for acquisition they currently all have their own implementations of how to create this grid.

This PR refactors the TileCreatorDialog's tile creation code into a utility Class which can help in the generation of grid points.

This PR also changes the AcquireMultipleRegion plugin to use this utility class instead of relying on its own grid creation functions. This fixes a number of bugs with how the plugin currently saves grid points.

- [x] Grid creator dialog now supports multiple 1-axis stages. Before it would just use the first one that was selected.

- [x] Fixed bug where position list dialog axis list would be left disabled if the tile creator dialog was exited out of.

- [x] Acquire Multiple Regions plugin now uses same grid creation as the tile creator dialog. This leads to more predictable acquisition and saving behavior for users.

- [x] Tile creator dialog previously determined z-values by drawing a plane through the first three points while ignoring the first. The dialog will now use Shephard interpolation. This should be equivalent to drawing a plane when only three points are specified. If more points are specified it will do a more complex interpolation. We could potentially do away with the four buttons in the current dialog and just have a single "Add point" button but this might be confusing.

The only thing missing at this point is that I'm not sure how to structure the API. Currently the tile creator dialog and the Acquire Multiple Regions plugin each create their own instance of of the utility class. In order to use the class you need access to:
`org.micromanager.internal.positionlist.utils.TileCreator`

as well as the ZGenerator.Type enum in:
`org.micromanager.internal.positionlist.utils.ZGenerator`

This should probably be rearranged.

### CODE REVIEW

**Comment by nanthony21** [comment]
@nicost , Do you have any feedback on what this needs in order to wrap up?

**Comment by nicost** [comment]
I should check out your branch, and run the code, but I didn't.  It looks alright to me, so I'll just pull it in;)

**Comment by nanthony21** [comment]
I'm unsure what happened here, did this get merged?

**Comment by nicost** [comment]
I thought I did, but apparently didn't;)  Thanks for the poke.  Should be in now.

**Pull request merged**
