### PR TITLE
Make TileCreator utility class

### PR DESCRIPTION
**Pull request by nanthony21**
While there are multiple components of micromanager that are interested in setting up a grid of positions for acquisition they currently all have their own implementations of how to create this grid.

This PR refactors the TileCreatorDialog's tile creation code into a utility Class which can help in the generation of grid points.

This PR also changes the AcquireMultipleRegion plugin to use this utility class instead of relying on its own grid creation functions. This fixes a number of bugs with how the plugin currently saves grid points.

### CODE REVIEW

**Comment by nicost** [comment]
I have a couple of problems with this PR.  I don't think that it is a good idea to make the core object static, hence, it is not a good idea to make the functions static.  We have been actively working in the past to remove the use of statics (and hey, why would one not want to have two cores?), and re-introducing such approaches is not good.  You could easily make TileCreator into a real class with a constructor that takes the core as a parameter.  Much cleaner that way.

In principle, it is not nice to add dependencies on internal code (i.e. make a plugin dependent on internal behavior of mmstudio).  I know that you can find dependencies on internal code in various places, but those are to be removed.  On the flip side, adding code to the API will need to be carefully examined, and we may not yet be ready to do so.  I could imagine, for instance, that the PositionListManager could provide some of this functionality (and the implementation of that API can call your internal TileCreator class).

Please try to avoid including the standard Netbeans headers:  
* To change this license header, choose License Headers in Project Properties.
Either delete, or better, include a real header including copyright and license information (there are many scattered throughout the source code).  In this case, it would also be good to indicate that most of the code was derived from a previous source file (and include the author info for that file).

**Comment by nanthony21** [comment]
Thanks for the feedback.

I guess I thought there could only be one core so it made sense use a static class. I'll go in and fix that. I'll also make sure to correct the license.

Is it alright if I keep the plugin's reference to an internal Class for now?

**Comment by nicost** [comment]
> Is it alright if I keep the plugin's reference to an internal Class for now?

Yes.  but let's think about which function(s) (if any) should go in the API ones you are done.

**Comment by nanthony21** [comment]
The above mentioned changes have been implemented now.

Based on looking at the existing code that uses this kind of functionality the most useful function is `createTiles` to actually generate a position list to be used.

The bounding box function also gets used often. This just gives the minimum and maximum coordinates that specify a bounding box for a set of input coordinates.

I'm not sure exactly how to go about implementing something into the API though.

**Comment by nicost** [comment]
I am a bit confused why the files ZGenerator, ZgeneratorAverage, ShepardInterpolator, and ZGeneratorShepard were removed.  That smells like loss of functionality.  I assume that Kurt used that code to set Z-values as well, something that was not done very well in the TileCreator.  Can you explain?

**Comment by nanthony21** [comment]
You're right that in its current state this PR loses the Zgenerator capability. I was more concerned with getting things to tile in a constistent manner so I just went with the implementation found in TileCreatorDlg.

It sounds like TileCreatorDlg might also benefit from something like the Zgenerators so maybe it would be best to merge that functionality into the TileCreator utility class so that both TileCreatorDlg and other plugins can use it?

**Comment by nicost** [comment]
It would be a shame to loose the capability.  For now, would it be possible to merge that capability back into the TileCreator utility class, and only use it in the AcquireMultipleRegion plugin?  That way the behavior for the user stays the same.  It may be good to also have it in the TileCreator Dialog, but there maybe issues there (for instance, the user should have the option whether or not to record the Z-position).

**Comment by nanthony21** [comment]
That sounds like a good idea. I will work in integrating the Zgenerators into the TileCreator but leave it as optional.

**Comment by nanthony21** [comment]
I'm going to close this for now and I'll open a new request when it's closer to being ready

**Pull request closed without merging**
