### PR TITLE
Allow pipeline processor Plugins to be enabled and disabled programmatically.

### PR DESCRIPTION
**Pull request by nanthony21**
This PR makes a few minor changes to the public methods of the pipelineFrame, which is accessible through the API.

`getPipelineConfigurators` will now return all configurators even if they are not enabled.

I have also added two methods to return only configurators that are enabled.

I have also added methods that allow the user to set the enabled status of a configurator based on it's position in the pipelineFrame.

See issues #29 and #30

### CODE REVIEW

**Comment by marktsuchida** [comment]
Perhaps I'm missing something, but please note that the two files changed here are both in "internal" packages, so they are *not* part of the API. (Note that in MMStudio code (like many other Java projects), we use packages with `internal` as part of their name to organize classes that need to be accessed from other packages *within* mmstudio, but are not intended for use by user code.)

If we want to allow pipeline configuration to be accessed programmatically from code outside mmstudio (e.g. plugins and scripts), then we need to define an API for that in an appropriate non-internal package.

In the case of the pipeline, at the moment the actual business code is in `org.micromanager.data`, but the concept of enabled/disabled is not part of the pipeline model -- it is just part of the user interface. Pipelines are created every time they are used and cannot change once they are created.

(Without this separation, we would have problems if the user edits the pipeline settings while images are being processed.)

There are a few methods in `DataManager` that allow control of what it calls the "application pipeline", which is roughly equivalent to what is displayed in the GUI. This is probably the place to add methods that control the enabled/disabled states of the processor *factories*. But actually having those methods in `DataManager` is probably already a design bug, because `org.micromanager.data` should never be doing things like opening GUI windows; we should probably deprecate and remove these in the future. Also, the `org.micromanager.data` should be agnostic about things like Live vs MDA.

So how can an API be added that enables/disables items in the pipeline configuration? Unfortunately, this will require some real work to do in a clean way.

The API should probably be added to `Studio` (or a new `PipelineManager` accessible from `Studio`) because the pipeline configuration (unlike `Pipeline`s) is a integrating concept of the overall application (something that would not be defined if using only the data management or only acquisition). We probably need a new data type, something like `PipelineTemplate`, which packages the list of pipeline plugins, their enabled/disabled state, and their configurations. Then we could have methods like `studio.getSnapLivePipelineTemplate()` or `studio.setMDAPipelineTemplate(tmpl)`. Note that this also requires that we can somehow package the settings for each pipeline plugin; we have such a mechanism for overlay plugins, but not yet for pipeline plugins, if I remember correctly. The `PipelineTemplate`, which will be quite useful on its own, would belong to `org.micromanager.data`

I'm open to other ways of architecting this, as long as it doesn't introduce undue coupling between concerns that should be separate.

**Comment by nanthony21** [comment]
You are correct that these are changes to internal packages, however `org.micromanager.internal.pipelineinterface.PipelineFrame` is already accessible through  `MMStudio.getPipelineFrame()` so my intention was just to add a few useful methods there.

I see now that the useful methods of `PipelineFrame` are also available through `DataManager`.

Adding something like a `PipelineManager` interface to `Studio` seems like a reasonable solution. If I'm not mistaken the `ConfiguratorWrapper` already packages together plugins, their configurations, and their enabled states. Could a `PipelineTemplate` essentially just be a list of `ConfiguratorWrapper`s along with methods for JSON encoding/decoding?

**Comment by marktsuchida** [comment]
Just to clarify, `MMStudio` is *also* internal, while the interface it implements (`Studio`) is public. User code, which has a reference to `Studio`, cannot call methods like `getPipelineFrame()` unless they cast to `org.micromanager.internal.MMStudio`, but the API itself doesn't guarantee that such a cast will succeed. This is why most API types are interfaces rather than classes, even though the vast majority are not supposed to be implemented by user code: by exposing only interfaces, we have the freedom to change the implementation class(es) without breaking existing user code, as long as the user code follows the rules. It is unfortunate that Java cannot enforce the rules (until Java 9).

You're right, it looks like `ProcessorConfigurator` already packages processor settings into a `PropertyMap`; I missed that.

But `ProcessorConfigurator` is a mutable object (settings may change at any time, e.g., via the GUI), so what would need to be packaged in `PipelineTemplate` (which should be a stand-alone description of how to create a pipeline without any external information) is the property map obtained from the configurator. The problem is that `ProcessorConfigurator` doesn't currently have a method to apply a configuration stored in a property map. We could add a `ProcessorConfigurator.setSettings(PropertyMap)`, but that would require updating all existing processor plugins.

Instead, I now realize that there might be a simpler solution. Given that we already have methods in `DataManager` (although I don't think that's the right place, let's let that be for now), what if we just add the following methods to `DataManager`?
- `List<ProcessorConfigurator> getApplicationPipelineConfigurators(boolean includeDisabled)`
- `List<ProcessorConfigurator> getLivePipelineConfigurators(boolean includeDisabled)`
- `boolean isApplicationPipelineStepEnabled(int index)`
- `void setApplicationPipelineStepEnabled(int index, boolean enabled)`
- `boolean isLivePipelineStepEnabled(int index)`
- `void setLivePipelineStepEnabled(int index, boolean enabled)`

These could just be API methods that forward to the methods you already added to the internal classes. The first method is just a variant of the existing method of the same name. The second method may not be strictly needed, but keeps things symmetric. The remaining 4 should be documented to indicate that the index applies to the list of steps including disabled steps.

The API still feels clumsy (e.g. `setApplicationPipeline` also affects the Live pipeline), but is probably the best that can be done without making much more disruptive changes.

**Comment by nanthony21** [comment]
For now I will work on adding the `DataManager` methods to this PR. I agree that in the long run though the current approach is going to make things a little clumsy.

While there is no `ProcessorConfigurator.setSettings(PropertyMap)` I think the same functionality basically exists in the `ProcessorPlugin.createConfigurator(PropertyMap)`

If we're willing to consider solutions that would require updating the existing processor plugins it seems like things could be simplified by consolidating how processor plugins are organized. Right now we have  `ProcessorConfigurator` implementations and the `ConfiguratorWrapper` class. Functionality that is useful to the user is spread between these classes. Could the functionality present in `ConfiguratorWrapper` be changed to an abstract base class that would be extended by each plugin's implementation of `ProcessorConfigurator`?

 The `ProcessorConfigurator` interface could have methods for `setEnabledStatus(boolean)`, `setEnabledLiveStatus(boolean)`, 'setSettings(PropertyMap)`, etc. Then `DataManager` could have a single method, `getPipeline` which would return `List<ProcessorConfigurator>` which would provide the user with a convenient way to change settings for each processor that is present in the pipeline.

**Comment by nanthony21** [comment]
@marktsuchida  The methods mentioned above have now been added to the DataManager interface. Everything seems to work as expected.

**Comment by nicost** [comment]
Sorry for the long delay!

**Comment by marktsuchida** [comment]
Sorry for not getting back. Looks good to me.

Ideally we would keep `getApplicationPipelineConfigurators` without arguments, for backward compatibility, but I'll let that slide since I don't think this is widely used (there wasn't much it could be used for before the new API you added!).

**Comment by nanthony21** [comment]
What needs to happen to get these changes into the documentation ? : https://valelab4.ucsf.edu/~MM/doc-2.0.0-gamma/mmstudio/org/micromanager/data/DataManager.html

**Comment by nicost** [comment]
Because of the errors below.  I just fixed them.  Hopefully the Javadoc will be updated tonight.

Generating doc/org/micromanager/data/DataManager.html...
./src/main/java/org/micromanager/data/DataManager.java:377: error: @param name not found
    * @param boolean determines whether or not to include configurators that are not currently enabled.
             ^
./src/main/java/org/micromanager/data/DataManager.java:387: error: @param name not found
    * @param boolean determines whether or not to include configurators that are not currently enabled.
             ^
./src/main/java/org/micromanager/data/DataManager.java:445: error: @param name not found
    * @param boolean of whether or not the plugin should be enabled.
             ^
./src/main/java/org/micromanager/data/DataManager.java:461: error: @param name not found
    * @param boolean of whether or not the plugin should be enabled.
             ^

**Pull request merged**
